name: Publish to Itch.io

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Godot Export
        id: export
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.2.2/Godot_v4.2.2-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.2.2/Godot_v4.2.2-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true
          cache: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: List contents of Web build directory (after export)
        run: ls -l /home/runner/.local/share/godot/archives/

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: web
          path: /home/runner/.local/share/godot/archives/Web.zip

      - name: Publish to itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: web
          ITCH_GAME: chaos-pool
          ITCH_USER: FollowTheDopamine
          PACKAGE: /home/runner/.local/share/godot/archives/Web.zip

      # Alternative publish action
      # - name: Publish to Itch
      #   uses: Ayowel/butler-to-itch@v1.0.0
      #   with:
      #     butler_key: ${{secrets.ITCHIO_TOKEN}}
      #     itch_user: FollowTheDopmaine
      #     itch_game: chaos-pool
      #     version: ${{ github.ref_name }}
      #     files: "${{ steps.export.outputs.archive_directory }}/Web.zip"
